# Generated by Django 5.2.6 on 2026-07-27 14:18

from django.db import migrations, models


def copy_hero_advantages(apps, schema_editor):
    HomePageSettings = apps.get_model("catalog", "HomePageSettings")

    for home_settings in HomePageSettings.objects.exclude(hero_advantage_group=None):
        group = home_settings.hero_advantage_group
        if group is None:
            continue

        titles = list(group.advantages.order_by("order", "pk").values_list("title", flat=True))
        if titles and not home_settings.hero_advantages_text:
            home_settings.hero_advantages_text = "\n".join(titles)
            home_settings.save(update_fields=["hero_advantages_text"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_public_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagesettings",
            name="hero_advantages_text",
            field=models.TextField(blank=True, verbose_name="Преимущества hero"),
        ),
        migrations.RunPython(copy_hero_advantages, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="advantage",
            name="group",
        ),
        migrations.RemoveField(
            model_name="homepagesettings",
            name="hero_advantage_group",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="page",
        ),
        migrations.RemoveField(
            model_name="service",
            name="page",
        ),
        migrations.RemoveField(
            model_name="application",
            name="page",
        ),
        migrations.RemoveField(
            model_name="step",
            name="page",
        ),
        migrations.RemoveField(
            model_name="workexample",
            name="page",
        ),
        migrations.DeleteModel(
            name="TelegramSubscriber",
        ),
        migrations.DeleteModel(
            name="Advantage",
        ),
        migrations.DeleteModel(
            name="AdvantageGroup",
        ),
        migrations.DeleteModel(
            name="Equipment",
        ),
        migrations.DeleteModel(
            name="Page",
        ),
    ]
