# Generated by Django 5.2.6 on 2026-07-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_advantage_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramSubscriber",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chat_id", models.CharField(max_length=128, unique=True, verbose_name="Telegram chat ID")),
                ("username", models.CharField(blank=True, max_length=255, verbose_name="Username")),
                ("first_name", models.CharField(blank=True, max_length=255, verbose_name="Имя")),
                ("last_name", models.CharField(blank=True, max_length=255, verbose_name="Фамилия")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("subscribed_at", models.DateTimeField(auto_now_add=True, verbose_name="Подписан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
            ],
            options={
                "verbose_name": "Подписчик Telegram",
                "verbose_name_plural": "Подписчики Telegram",
                "ordering": ("-updated_at", "-pk"),
            },
        ),
    ]
