# Generated by Django 5.2.6 on 2026-07-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_telegramsubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='about_image_1_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt первой картинки блока о нас'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='about_image_1_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='Путь к первой картинке блока о нас'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='about_image_2_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt второй картинки блока о нас'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='about_image_2_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='Путь ко второй картинке блока о нас'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='about_image_3_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt третьей картинки блока о нас'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='about_image_3_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='Путь к третьей картинке блока о нас'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='contact_image_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt картинки блока контактов'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='contact_image_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='Путь к картинке блока контактов'),
        ),
    ]
