# Generated by Django 5.2.6 on 2026-07-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_homepagesettings_about_image_1_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='max_url',
            field=models.URLField(blank=True, verbose_name='Max URL'),
        ),
    ]
